<?php
/**
 * PetsApiInterface
 * PHP version 7.1.3
 *
 * @category Class
 * @package  App\OpenApiBundle
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Swagger Petstore
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\OpenApiBundle\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use App\OpenApiBundle\Model\Error;
use App\OpenApiBundle\Model\Pet;

/**
 * PetsApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  App\OpenApiBundle\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface PetsApiInterface
{

    /**
     * Operation createPets
     *
     * Create a pet
     *
     * @param  \int $responseCode     The HTTP response code to return
     * @param  \array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     */
    public function createPets(&$responseCode, array &$responseHeaders);

    /**
     * Operation listPets
     *
     * List all pets
     *
     * @param  \int $limit  How many items to return at one time (max 100) (optional)
     * @param  \int $responseCode     The HTTP response code to return
     * @param  \array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return \App\OpenApiBundle\Model\Pet[]
     */
    public function listPets($limit = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation showPetById
     *
     * Info for a specific pet
     *
     * @param  \string $petId  The id of the pet to retrieve (required)
     * @param  \int $responseCode     The HTTP response code to return
     * @param  \array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return \App\OpenApiBundle\Model\Pet
     */
    public function showPetById($petId, &$responseCode, array &$responseHeaders);
}
